### ISSUE TITLE
Where is the repo for the Unibit docs?

### ISSUE THREAD

**Issue by knightspore** [stackbit/unibit#25]
I've found some errors in the docs, looking for a repo where I can submit a PR to change these.

**Comment by smnh** [comment]
Hi @knightspore 

At the moment, the [unibit docs](https://www.stackbit.com/docs/unibit/) included with the rest of the stackbit docs and therefore private. Let me know what fixes you want to introduce to the docs and I will add them.

**Comment by knightspore** [comment]
Hey mate

So the way your docs is laid out, this last example should read: 
Output
```njk
foo
```
not `someString`, as it differs from the other examples. It's describiing which variable will be shown, not the actual output (which the first example in the screenshot does).

![image](https://user-images.githubusercontent.com/51886151/106899510-1d0c3e00-66fe-11eb-914d-8dfd2ca6163b.png)

**Comment by smnh** [comment]
Thanks @knightspore 
Fix to the docs is on the way!
